# Python CI workflow for project1/backend
name: Python CI

on:
  push:
    paths:
      - 'projects/project1/backend/**'
  pull_request:
    paths:
      - 'projects/project1/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
      - name: Run tests
        run: |
          if [ -f tests ]; then pytest; else echo 'No tests found.'; fi
